# -*- mode: ruby -*-
# vi: set ft=ruby  
#Vagrant File which spins up 7 Instances with Public_network Ips and  ubuntu installed on them.
nodes = [  
  { :hostname => 'server1', :ip => '192.168.0.41', :box => 'precise32' },
  { :hostname => 'server2', :ip => '192.168.0.42', :box => 'precise32' },
  { :hostname => 'server3', :ip => '192.168.0.43', :box => 'precise32' },
  { :hostname => 'server4', :ip => '192.168.0.44', :box => 'precise32' },
  { :hostname => 'server5', :ip => '192.168.0.45', :box => 'precise32' },
  { :hostname => 'server6', :ip => '192.168.0.46', :box => 'precise32' },
  { :hostname => 'server7', :ip => '192.168.0.47', :box => 'precise32' },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "ubuntu/trusty64"
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: node[:ip]
      nodeconfig.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    end
  end
end